apiVersion: v1
kind: Secret
metadata:
  name: laeb-secrets
  namespace: laeb
type: Opaque
data:
  JWT_SECRET: ZGV2LXNlY3JldC1jaGFuZ2UtbWUtaW4tcHJvZHVjdGlvbg==
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  SERVICE_DB_PASSWORD: c2VydmljZXBhc3M=
  MINIO_ACCESS_KEY: bWluaW9hZG1pbg==
  MINIO_SECRET_KEY: bWluaW9hZG1pbg==
  IDENTITY_DATABASE_URL: cG9zdGdyZXNxbCtwc3ljb3BnOi8vaWRlbnRpdHlfdXNlcjpzZXJ2aWNlcGFzc0Bwb3N0Z3Jlczo1NDMyL2lkZW50aXR5
  PROFILE_DATABASE_URL: cG9zdGdyZXNxbCtwc3ljb3BnOi8vcHJvZmlsZV91c2VyOnNlcnZpY2VwYXNzQHBvc3RncmVzOjU0MzIvcHJvZmlsZQ==
  CATALOG_DATABASE_URL: cG9zdGdyZXNxbCtwc3ljb3BnOi8vY2F0YWxvZ191c2VyOnNlcnZpY2VwYXNzQHBvc3RncmVzOjU0MzIvY2F0YWxvZw==
  ORDER_DATABASE_URL: cG9zdGdyZXNxbCtwc3ljb3BnOi8vb3JkZXJzX3VzZXI6c2VydmljZXBhc3NAcG9zdGdyZXM6NTQzMi9vcmRlcnM=
  WALLET_DATABASE_URL: cG9zdGdyZXNxbCtwc3ljb3BnOi8vd2FsbGV0X3VzZXI6c2VydmljZXBhc3NAcG9zdGdyZXM6NTQzMi93YWxsZXQ=
  TRADING_DATABASE_URL: cG9zdGdyZXNxbCtwc3ljb3BnOi8vdHJhZGluZ191c2VyOnNlcnZpY2VwYXNzQHBvc3RncmVzOjU0MzIvdHJhZGluZw==
  FESTIVAL_DATABASE_URL: cG9zdGdyZXNxbCtwc3ljb3BnOi8vZmVzdGl2YWxfdXNlcjpzZXJ2aWNlcGFzc0Bwb3N0Z3Jlczo1NDMyL2Zlc3RpdmFs
